//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionRate : IEquatable<ConstructionRate>
    {
        public int Id { get; set; }
        public double Value { get; set; }
        public System.DateTime TimeOfCommit { get; set; }
        public virtual Expert Expert { get; set; }
        public virtual Construction Construction { get; set; }

        public ConstructionRate()
        {
            Value = 0.0;
            TimeOfCommit = DateTime.Now;
        }

        public ConstructionRate(double value) : this()
        {
            Value = value;
        }

        public bool Equals(ConstructionRate other)
        {
            return Value == other.Value && TimeOfCommit == other.TimeOfCommit;
        }
    }
}
